[workspace]
members = [
    "rust/vectordb",
    "rust/ffi/node"
]
resolver = "2"

[workspace.dependencies]
lance = { git = "https://github.com/lancedb/lance.git", branch = "gsilvestrin/win_remove_vcpkg" }
arrow-array = "42.0"
arrow-data = "42.0"
arrow-schema = "42.0"
arrow-ipc = "42.0"
object_store = "0.6.1"
