[workspace]
members = [
    "rust/vectordb",
    "rust/ffi/node"
]
resolver = "2"

[workspace.dependencies]
lance = "0.5.3"
arrow-array = "40.0"
arrow-data = "40.0"
arrow-schema = "40.0"
arrow-ipc = "40.0"
object_store = "0.6.1"
