site_name: LanceDB Docs
repo_url: https://github.com/lancedb/lancedb
repo_name: lancedb/lancedb
docs_dir: src

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [../python]
        selection:
          docstring_style: numpy
        rendering:
          heading_level: 4
          show_source: false
          show_symbol_type_in_heading: true
          show_signature_annotations: true
          show_root_heading: true
          members_order: source
        import:
          # for cross references
          - https://arrow.apache.org/docs/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
- mkdocs-jupyter

markdown_extensions:
- admonition
- footnotes
- pymdownx.superfences
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- md_in_html

nav:
- Home: index.md
- Basics: basic.md
- Embeddings: embedding.md
- Python full-text search: fts.md
- Integrations:
  - Pandas and PyArrow: python/arrow.md
  - DuckDB: python/duckdb.md
  - LangChain 🦜️🔗: https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/lancedb.html
  - LangChain JS/TS 🦜️🔗: https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/lancedb
  - LlamaIndex 🦙: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/LanceDBIndexDemo.html
  - Pydantic: python/pydantic.md
  - Voxel51: integrations/voxel51.md
- Python examples:
  - YouTube Transcript Search: notebooks/youtube_transcript_search.ipynb
  - Documentation QA Bot using LangChain: notebooks/code_qa_bot.ipynb
  - Multimodal search using CLIP: notebooks/multimodal_search.ipynb
  - Serverless QA Bot with S3 and Lambda: examples/serverless_lancedb_with_s3_and_lambda.md
  - Serverless QA Bot with Modal: examples/serverless_qa_bot_with_modal_and_langchain.md
- Javascript examples:
  - YouTube Transcript Search: examples/youtube_transcript_bot_with_nodejs.md
  - TransformersJS Embedding Search: examples/transformerjs_embedding_search_nodejs.md

- Guides:
  - Tables: guides/tables.md
  - Vector Search: search.md
  - SQL filters: sql.md
  - Indexing: ann_indexes.md
- API references:
  - Python API: python/python.md
  - Javascript API: javascript/modules.md

extra_css:
  - styles/global.css
