name: run-tests

description: "Install lance wheel and run unit tests"
inputs:
  python-minor-version:
    required: true
    description: "8 9 10 11 12"
  integration:
    required: false
    description: "Run integration tests"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install lancedb
      shell: bash
      run: |
        pip3 install $(ls target/wheels/lancedb-*.whl)[tests,dev]
    - name: Setup localstack for integration tests
      if: ${{ inputs.integration == 'true' }}
      shell: bash
      working-directory: .
      run: |
        docker-compose compose up --detach
        sleep 10
    - name: pytest
      shell: bash
      run: pytest -m "not slow" -x -v --durations=30 python/python/tests
