name: Python

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - python/**
      - .github/workflows/python.yml
jobs:
  linux:
    timeout-minutes: 30
    strategy:
      matrix:
        python-minor-version: [ "8", "9", "10", "11" ]
    runs-on: "ubuntu-22.04"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ matrix.python-minor-version }}
    - name: install tantivy from source
      run: |        
        git clone https://github.com/quickwit-oss/tantivy-py
        cd tantivy-py
        pip install -e .
    - name: Install lancedb
      run: |
        pip install -e ".[fts]"
        pip install pytest
    - name: Run tests
      run: pytest -x -v --durations=30 tests
  mac:
    timeout-minutes: 30
    runs-on: "macos-12"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: install tantivy from source
      run: |        
        git clone https://github.com/quickwit-oss/tantivy-py
        cd tantivy-py
        pip install -e .
    - name: Install lancedb
      run: |
        pip install -e ".[fts]"
        pip install pytest
    - name: Run tests
      run: pytest -x -v --durations=30 tests