name: Trigger vectordb-recipers workflow
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger vectordb-recipes workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.VECTORDB_RECIPES_ACTION_TOKEN }}
          script: |
            const result = await github.rests.actions.createWorkflowDispatch({
                'lancedb',
                'vectordb-recipes',
                'workflows/TEMP.yml',
                'main',
            });
            console.log(result);