name: Trigger vectordb-recipers workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger vectordb-recipes workflow
        run: |
          curl -X POST https://api.github.com/repos/lancedb/vectordb-recipes/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Content-Type: application/json" \
          -u ${{ secrets.VECTORDB_RECIPES_ACTION_TOKEN }} \
          -d '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3